name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  id-token: write # needed for requesting the JWT
  contents: read # required for actions/checkout

jobs:
  DeployCdkApplication:
    runs-on: ubuntu-latest
    steps:
      - name: git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.OIDC_IDP_IAM_ROLE }}
          role-session-name: deployment-session
          aws-region: ${{ env.AWS_REGION }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: npm ci
        run: npm install
      - name: cdk
        run: |
          npm run cdk -- ${{env.CDK_COMMAND}} ${{env.CDK_FLAGS}} \
            --context "cronHour=${{env.CRON_HOUR}}" \
            --context "cronMinute=${{env.CRON_MINUTE}}" \
            --context "cronDay=${{env.CRON_DAY}}" \
            --context "logLevel=${{env.LOG_LEVEL}}" \
            --context "logRetentionPeriod=${{env.LOG_RETENTION_PERIOD}}" \
            --context "logGroupPattern=${{env.LOG_GROUP_PATTERN}}"
